build:
  stage: build
  image: gcc:latest

  variables:
    CTEST_OUTPUT_ON_FAILURE: 1
    VCPKG_ROOT: "$CO_PROJECT_DIR/vcpkg"

  cache:
    key:
      files:
        - vcpkg.json
      prefix: "vcpkg-linux"
    paths:
      - vcpkg/
      - .cache/vcpkg/
      - build/vcpkg_installed

  before_script:
    - apt-get update && apt-get install -y cmake ninja-build curl zip lcov git

  script:
    - |
      if [ ! -d "$VCPKG_ROOT" ]; then
        git clone https://github.com/microsoft/vcpkg $VCPKG_ROOT
      fi
      $VCPKG_ROOT/bootstrap-vcpkg.sh
    - cmake -S . -B build --preset gcc-debug -DENABLE_TEST_COVERAGE=ON
    - cmake --build build

  artifacts:
    paths:
      - build/
    expire_in: 1 hour

test:
  stage: test
  image: gcc:latest
  needs: [ build ]

  before_script:
    - apt-get update && apt-get install -y cmake

  script:
    - ctest --test-dir build/tests/ --build-config Debug

coverage:
  stage: coverage
  image: gcc:latest
  needs: [ test ]

  before_script:
    - apt-get update && apt-get install -y cmake lcov

  script:
    - |
      lcov --capture \
           --directory build/ \
           --ignore-errors mismatch \
           --exclude '/usr/*' \
           --exclude '*/vcpkg*/*' \
           --exclude '*/tests/*' \
           --output-file coverage.info
    - lcov --summary coverage.info

  coverage: '/lines[.]+: \d+\.\d+%/'

  artifacts:
    paths:
      - coverage.info
    expire_in: 1 week

  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"