lint:
  stage: lint
  needs: [ build ]
  before_script:
    - apt-get update
    - apt-get install -y clang-format clang-tidy

  script:
    - FILES=$(git ls-files '*.cpp' '*.hpp' '*.h' '*.cuh' '*.cu')
    - |
      [ -z "$FILES" ] || clang-format --dry-run --Werror $FILES
    - FILES=$(git ls-files '*.cpp' '*.hpp' '*.h')
    - |
      [ -z "$FILES" ] || clang-tidy $FILES -p build --warnings-as-errors=*