lint:
  stage: lint
  image: ubuntu:latest

  before_script:
    - apt-get update
    - apt-get install -y git clang-format

  script:
    - FILES=$(git ls-files '*.cpp' '*.hpp' '*.h' '*.cuh' '*.cu')
    - |
      [ -z "$FILES" ] || clang-format --dry-run --Werror $FILES
