pages:
  stage: deploy
  needs: [ build ]

  before_script:
    - cmake --build build --target docs

  script:
    - mkdir -p public
    - cp -r build/docs/html/* public/

  artifacts:
    paths:
      - public
  only:
    - main