pages:
  stage: deploy
  image: gcc:latest
  before_script:
    - apt-get update && apt-get install -y cmake doxygen

  script:
    - cmake -S docs -B build
    - cmake --build build --target docs
    - mkdir -p public
    - cp -r build/docs/html/* public/

  artifacts:
    paths:
      - public
  only:
    - main