name: Coverage
on:
  pull_request:
  push:
    branches: [ main, master ]

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ${{ env.VCPKG_ROOT }}
            ~/.cache/vcpkg
            build/vcpkg_installed
          key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-

      - name: Bootstrap vcpkg
        run: |
          if [ ! -d "$VCPKG_ROOT" ]; then
            git clone https://github.com/microsoft/vcpkg $VCPKG_ROOT
          fi
          $VCPKG_ROOT/bootstrap-vcpkg.sh
        shell: bash

      - name: Configure
        run: cmake -S . -Bbuild --preset gcc-debug -DENABLE_TEST_COVERAGE=ON

      - name: Build
        run: cmake --build build --target build_tests

      - name: test
        run: |
          ctest --test-dir build/tests --build-config Debug

      - name: Capture coverage
        run: |
          apt install lcov -y
          lcov --capture \
               --directory build/tests \
               --output-file coverage.info
          lcov --remove coverage.info \
               '/usr/*' \
               '*/vcpkg/*' \
               '*/vcpkg_installed/*'
               --output-file coverage.info

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          files: coverage.info
